micronaut:
  application:
    name: expen-share
  server:
    port: 8080

datasources:
  default:
    url: jdbc:h2:mem:expen-share;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true

kafka:
  bootstrap:
    servers: localhost:9092

logger:
  levels:
    ROOT: INFO