CREATE TABLE group_members(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT,
    user_id     BIGINT,
    added_at    TIMESTAMP NOT NULL,

    CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_group_user  UNIQUE (group_id, user_id)
)