CREATE TABLE expenses(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT,
    paid_by     BIGINT,
    amount      DECIMAL(18,2)   NOT NULL,
    description VARCHAR(255)    NOT NULL,
    split_type  VARCHAR(10)      NOT NULL,
    created_at  TIMESTAMP       NOT NULL,

    CONSTRAINT fk_group_expenses FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_expenses FOREIGN KEY (paid_by) REFERENCES users(id)
);