CREATE TABLE expense_shares(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      BIGINT,
    user_id         BIGINT,
    share_amount    DECIMAL(18,2)   NOT NULL,

    CONSTRAINT fk_group_expense_shares FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_expense_shares FOREIGN KEY (user_id) REFERENCES users(id)
);