CREATE TABLE settlements(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT,
    from_user_id    BIGINT,
    to_user_id      BIGINT,
    amount          DECIMAL(18,2)   NOT NULL,
    method          VARCHAR(20)     NOT NULL,
    note            VARCHAR(255),
    reference       VARCHAR(64),
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMP       NOT NULL,
    confirmed_at    TIMESTAMP,

    CONSTRAINT fk_group_settlements FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_from_user FOREIGN KEY (from_user_id) REFERENCES users(id),
    CONSTRAINT fk_to_user FOREIGN KEY (to_user_id) REFERENCES users(id)

);